# Generated by Django 4.0.3 on 2022-05-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='originImage',
            field=models.ImageField(null=True, upload_to='userimage/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
