# Generated by Django 4.0.3 on 2022-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_userimage_originimage_alter_userimage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='originImage',
            field=models.ImageField(null=True, upload_to='User/test/', verbose_name='img'),
        ),
    ]
