# Generated by Django 4.0.3 on 2022-05-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_userimage_originimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='originImage',
        ),
    ]
